sudo: required
language: cpp
dist: trusty
branches:
  except:
  - "/^appveyor.*$/"
before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
- sudo apt-get update -qq
install:
- sudo apt-get install -qq libgsl0-dev qt59base qt59tools qt59svg
- source /opt/qt59/bin/qt59-env.sh
- cd $TRAVIS_BUILD_DIR/..
- svn checkout svn://svn.code.sf.net/p/qwt/code/branches/qwt-6.1 qwt
- cd qwt
- QWT_ROOT_DIR=`pwd`
- LD_LIBRARY_PATH=$(readlink -f lib):$LD_LIBRARY_PATH
- qmake
- make -j$(nproc)
script:
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
- cmake .. -DQWT_ROOT_DIR=$QWT_ROOT_DIR -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:STRING=dist
- echo $PROJECT_VERSION
- make -j$(nproc)
- make install
- wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt*.AppImage
- ldd dist/usr/bin/sigmaspectra
- "./linuxdeployqt-*.AppImage dist/sigmaspectra.desktop -bundle-non-qt-libs -no-translations"
- "./linuxdeployqt-*.AppImage dist/sigmaspectra.desktop -appimage"
- find ./dist -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f
  2-3 | sort | uniq
after_success:
- ls -lh
- VERSION=$(sed -ne 's/.*VERSION "\([0-9.]\+\)".*/\1/p' ../CMakeLists.txt)
- GITHASH=$(git rev-parse --short HEAD)
- curl --upload-file ./SigmaSpectra-*.AppImage https://transfer.sh/SigmaSpectra-x86_64.AppImage
- mv SigmaSpectra-*.AppImage SigmaSpectra-v$VERSION-$GITHASH-x86_64.AppImage
deploy:
  provider: releases
  api_key:
    secure: y75Euo8/a4vZOYK3axokBZP06Kd1Ll2vLUTUezIhqF0qCtnZKfo30jAW6QDGUQzfIf9KJHAVetl/ufjuNUTyK3GhZP4C865lfdeTP8XyNrq5gIspmYmMEphUcsKaTRc2tUlAL2dbHViR1q4f6l92Kt1MSlKUkFKa38peRhXwBr9MNG7kFstbUHJnEnLVgI1LOeePJhEiGaOtx1VAav+woiaEt2E7wxaoCCIg2p46HD3iX2diOPAcwPSR4BVVMeFBRzy5e9dQ0PeRIF2rUdGjkfGwS60mIovRL1qYRj/rBJUjc6RfQTtKHSwYjQbVjw9qnEFinpWfMPjicqp4I1oZL+g0/aKiOzSK6WqecVGGjFjFhhGUHmFBa3dDh56URXqWiQh5VeHlaZMIq3ix3zIuJTTJ5YcwaV50w8SLV2xZCTJXwIyZ0RMUr2Sv2S68migwxUDVpvMFkdAxlB3Gce6bApry+pk81Po9+hD5qo+SKGZWy2zOl38ieHSgoQTWO/bxZa/A+cJmW9dgkKfPruU85QE+VYPYrK/0IhL0piezv0feXCDY9nkhTXU+mjDjd9wrufcEQTR2SnrC7HfYE91n3tfcDlMzujAOUY9eJlvWTGE/NnJpTGbV4LaEjp7Pdz5QfSathAnlkKub9iZwXx6iFgqIimUEe6rBGthNN2O18m8=
  file: SigmaSpectra-v$VERSION-$GITHASH-x86_64.AppImage
  on:
    repo: arkottke/sigmaspectra
