version: '{build}'

branches:
    except:
        - /^travis.*$/

init:
    - git config --global core.autocrlf input

clone_depth: 1

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2015

environment:
    fast_finish: true
    matrix:
        - PLATFORM: x86
          QT5: C:\Qt\5.9\msvc2015
          CMAKE_GENERATOR: "NMake Makefiles"
        - PLATFORM: x64
          QT5: C:\Qt\5.9\msvc2015_64
          CMAKE_GENERATOR: "NMake Makefiles"

configuration: Release
    
# Configure git linebreaks
cache:
    - c:\projects\gsl -> appveyor.yml
    - c:\projects\qwt -> appveyor.yml

install:
    - contrib\install_appveyor_dependencies.bat

build_script:
    - MKDIR sigmaspectra\build
    - CD sigmaspectra\build
    - cmake -DGSL_ROOT_DIR=%GSL_ROOT_DIR% -DQWT_ROOT_DIR=%QWT_ROOT_DIR% -G "%CMAKE_GENERATOR%" ..
    - cmake --build . --target install
    - cmake --build . --target installer
    - cmake --build . --target archive

artifacts:
    - path: build\SigmaSpectra-*.zip
      name: Zip Archive

    - path: build\SigmaSpectra-*.msi
      name: Installer

deploy:
    description: 'Release description'
    provider: GitHub
    auth_token:
        secure: e/Uc+Q6xQyd6u9tBsvh6UlYfmmJgSL/cmoq6dhS5NHkgQAvETilqfDsO2euzazfp
    draft: true
    prerelease: false
    on:
        # branch: /v\d+\.\d+\.\d+/       # Match against the version tag
        branch: master
        appveyor_repo_tag: true        # deploy on tag push only

