version: '{build}'

branches:
    except:
        - /^travis.*$/

init:
    - git config --global core.autocrlf input
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

clone_depth: 1

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2015

environment:
    fast_finish: true
    matrix:
        - CMAKE_GENERATOR: "MinGW Makefiles"
          QT5: C:\Qt\5.9\mingw53_32
          ARCH: x86

configuration: Release
    
# Configure git linebreaks
cache:
    - c:\projects\gsl -> appveyor.yml
    - c:\projects\qwt -> appveyor.yml
    - c:\Program Files (x86)\GSL -> appveyor.yml

install:
    # Remove sh.exe from the path otherwise CMake will complain:
    # "sh.exe was found in your PATH, here: C:/Program Files/Git/usr/bin/sh.exe"
    # and the MinGW build will not work (the Visual Studio build does not care).
    # See http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
    # The entire directory containing sh.exe could be removed from the PATH environment:
    # - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    # However, this will also remove all other programs in this directory from the PATH.
    # In particular "patch" is still required.
    # So, just rename sh.exe:
    - ren "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe
    # Add Qt, MinGW, and WiX to PATH
    - set PATH=%QT5%\bin;C:\MinGW\bin;C:\Program Files (x86)\WiX Toolset v3.11\bin;%PATH%
    - cd c:\projects
      # Install GSL
    - git clone https://github.com/ampl/gsl.git
    - cd gsl
    - cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE="Release" -G "%CMAKE_GENERATOR%" .
    - mingw32-make -j2 install
    - set GSL_ROOT_DIR="%ProgramFiles(x86)%\GSL"
    - cd ..
      # Install Qwt
    - svn export svn://svn.code.sf.net/p/qwt/code/branches/qwt-6.1 qwt
    - cd qwt
    - qmake
    - mingw32-make -j2
    - set QWT_ROOT_DIR=%cd%
    - cd ..

build_script:
    - mkdir sigmaspectra\build
    - cd sigmaspectra\build
    - cmake -DGSL_ROOT_DIR=%GSL_ROOT_DIR% -DQWT_ROOT_DIR=%QWT_ROOT_DIR% -G "%CMAKE_GENERATOR%" ..
    - mingw32-make -j2 release

deploy:
    description: 'Release description'
    provider: GitHub
    auth_token:
        secure: e/Uc+Q6xQyd6u9tBsvh6UlYfmmJgSL/cmoq6dhS5NHkgQAvETilqfDsO2euzazfp
    draft: true
    prerelease: false
    on:
        # branch: /v\d+\.\d+\.\d+/       # Match against the version tag
        branch: master
        appveyor_repo_tag: true        # deploy on tag push only

on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
