# version format
version: '{build}'

platform: x64
environment:
  fast_finish: true
  matrix:
#  - ARCH: "i686"
  - ARCH: "x86_64"

configuration: Release
    
# Configure git linebreaks
init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
# Install dependencies
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - pacman -S --noconfirm --quiet pacman-mirrors
  - pacman -Syu --noconfirm --quiet 
  # Need to re-run Syu after update
  - pacman -Syu --noconfirm --quiet 
  - pacman -S --noconfirm --quiet mingw-w64-%ARCH%-qwt-qt5 mingw-w64-%ARCH%-gsl mingw-w64-%ARCH%-qt5

build_script:
  - mkdir build
  - cd build
  - cmake -G "MinGW Makefiles" ..
  - mingw32-make installer

artifacts:
    - path: SigmaSpectra-mingw64-*.exe
      name: SigmaSpectra Installer (64-bit)

    - path: SigmaSpectra-mingw64-*.zip
      name: SigmaSpectra Archive (64-bit)

    - path: SigmaSpectra-mingw32-*.exe
      name: SigmaSpectra Installer (32-bit)

    - path: SigmaSpectra-mingw32-*.zip
      name: SigmaSpectra Archive (32-bit)

deploy:
    description: 'Release description'
    provider: GitHub
    auth_token:
        secure: e/Uc+Q6xQyd6u9tBsvh6UlYfmmJgSL/cmoq6dhS5NHkgQAvETilqfDsO2euzazfp
    draft: true
    prerelease: false
    on:
        # branch: /v\d+\.\d+\.\d+/       # Match against the version tag
        branch: master
        appveyor_repo_tag: true        # deploy on tag push only
