version: '{build}'

branches:
    except:
        - /^travis.*$/

init:
    - git config --global core.autocrlf input

clone_depth: 1

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2015

environment:
    fast_finish: true
    matrix:
        - CMAKE_GENERATOR: "MinGW Makefiles"
          MINGW: C:\Qt\Tools\mingw530_32\bin
          QT5: C:\Qt\5.9\mingw53_32

configuration: Release
    
# Configure git linebreaks
cache:
    - c:\projects\gsl -> appveyor.yml
    - c:\projects\qwt -> appveyor.yml

install:
    # Remove sh.exe from the path otherwise CMake will complain:
    # "sh.exe was found in your PATH, here: C:/Program Files/Git/usr/bin/sh.exe"
    # and the MinGW build will not work (the Visual Studio build does not care).
    # See http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
    # The entire directory containing sh.exe could be removed from the PATH environment:
    # - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    # However, this will also remove all other programs in this directory from the PATH.
    # In particular "patch" is still required.
    # So, just rename sh.exe:
    - REN "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe
    # Add Qt, MinGW, and WiX to PATH
    - SET PATH=%QT5%\bin;%MINGW%\bin;C:\Program Files (x86)\WiX Toolset v3.11\bin;%PATH%
    - CD c:\projects
      # Install GSL
    - IF EXIST gsl (CD gsl & git pull) ELSE (git clone https://github.com/ampl/gsl.git & CD gsl)
    - cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE="Release" -G "%CMAKE_GENERATOR%" .
    - cmake --build . --target install
    - SET GSL_ROOT_DIR="%ProgramFiles(x86)%\GSL"
    - CD ..
      # Install Qwt
    - IF EXIST qwt (CD qwt & svn update) ELSE (svn co -r HEAD svn://svn.code.sf.net/p/qwt/code/branches/qwt-6.1 qwt & CD qwt)
    - qmake
    - mingw32-make -j2
    - set QWT_ROOT_DIR=%CD%
    - CD ..

build_script:
    - MKDIR sigmaspectra\build
    - CD sigmaspectra\build
    - cmake -DGSL_ROOT_DIR=%GSL_ROOT_DIR% -DQWT_ROOT_DIR=%QWT_ROOT_DIR% -G "%CMAKE_GENERATOR%" ..
    - cmake --build . --target install
    - cmake --build . --target installer
    - cmake --build . --target archive

artifacts:
    - path: build\SigmaSpectra-*.zip
      name: Zip Archive

    - path: build\SigmaSpectra-*.msi
      name: Installer

deploy:
    description: 'Release description'
    provider: GitHub
    auth_token:
        secure: e/Uc+Q6xQyd6u9tBsvh6UlYfmmJgSL/cmoq6dhS5NHkgQAvETilqfDsO2euzazfp
    draft: true
    prerelease: false
    on:
        # branch: /v\d+\.\d+\.\d+/       # Match against the version tag
        branch: master
        appveyor_repo_tag: true        # deploy on tag push only

