version: '{build}'

branches:
    except:
        - /^travis.*$/

init:
    - git config --global core.autocrlf input
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

shallow_clone: true

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2015

environment:
    fast_finish: true
    matrix:
        - CMAKE_GENERATOR: "Visual Studio 14 2015"
          QT5: C:\Qt\5.9\msvc2015
          ARCH: x86
          #       - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
          #         QT5: C:\Qt\5.8\msvc2015_64

configuration: Release
    
# Configure git linebreaks
cache:
    - c:\projects\gsl -> appveyor.yml
    - c:\projects\qwt -> appveyor.yml

install:
    - set PATH=%QT5%\bin;%PATH%
    - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
    - cd c:\projects
      # Install GSL
    - git clone https://github.com/ampl/gsl.git
    - pushd gsl
    - cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE="Release" -DGSL_INSTALL:BOOL=ON .
    - msbuild INSTALL.vcxproj /p:Configuration=Release /m
    - popd
      # Install Qwt
    - svn export svn://svn.code.sf.net/p/qwt/code/branches/qwt-6.1 qwt
    - pushd qwt
    - qmake & nmake
    - set QWT_ROOT_DIR=%cd%
    - popd

build_script:
    - mkdir sigmaspectra\build
    - pushd sigmaspectra\build
    - cmake .. -DGSL_INSTALL "%ProgramFiles(x86)%\GSL"  -DQWT_ROOT_DIR=%QWT_ROOT_DIR%

deploy:
    description: 'Release description'
    provider: GitHub
    auth_token:
        secure: e/Uc+Q6xQyd6u9tBsvh6UlYfmmJgSL/cmoq6dhS5NHkgQAvETilqfDsO2euzazfp
    draft: true
    prerelease: false
    on:
        # branch: /v\d+\.\d+\.\d+/       # Match against the version tag
        branch: master
        appveyor_repo_tag: true        # deploy on tag push only

on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
